export const resource_card_title = "选择资源"
export const resources_selecter_model = "数据模型"
export const resources_selecter_source = "数据表"
export const resources_selecter_model_switch_open = "全部展开"
export const resources_selecter_model_switch_close = "全部折叠"

export const model_header_btn_sub = "创建子查询"
export const model_header_btn_union = "创建集合查询"
export const model_header_btn_cancel = "撤销"
export const model_header_btn_redo = "重做"

export const option_title_join = "关联"
export const option_title_setop = "集合"

export const option_setting = "设置"
export const option_delete = "删除"

export const option_join_title = "关联"
export const option_join_using = "切换使用USING"
export const option_join_on = "切换使用ON"
export const option_join_exp_on_group = "选择来源表"
export const option_join_exp_on_db = "选择字段"
export const option_join_exp_on_auto_search = "快速查找"
export const option_join_exp_on_db_text_hint = "自定义内容"

export const option_table_alias = "别名"
export const option_table_field_select = "字段选择"

export const option_select_tab_select_items = "查询字段"
export const option_select_tab_where = "过滤条件"
export const option_select_tab_having = "筛选条件"
export const option_select_tab_groupby = "分组字段"
export const option_select_tab_orderby = "排序列表"
export const option_select_tab_select_items_select = "选择需要添加的查询字段"
export const option_select_tab_select_items_select_search = "快速查找"
export const option_select_tab_select_items_table_name = "列名"
export const option_select_tab_select_items_table_alias = "别名"
export const option_select_tab_select_items_table_as = "AS"
export const option_select_tab_select_items_table_from = "来源"
export const option_select_tab_select_items_table_datasource = "数据源"
export const option_select_tab_select_items_table_no_row = "请添加需要查询的字段"