export const resource_card_title = "选择资源"
export const resources_selecter_model = "数据模型"
export const resources_selecter_source = "数据表"
export const resources_selecter_model_switch_open = "全部展开"
export const resources_selecter_model_switch_close = "全部折叠"

export const model_header_btn_sub = "创建子查询"
export const model_header_btn_union = "创建集合查询"
export const model_header_btn_cancel = "撤销"
export const model_header_btn_redo = "重做"