import * as React from 'react'
import * as classnames from 'classnames'
import * as uuid from 'uuid'

import { cn } from '../../../text'
import { connect2 } from '../../../../common/connect'
import { DataModel, DataDefine } from '../../../../common/data'
import { SQLParser } from '../../../../common/data/utils'
import { option as optionAction } from '../../../../common/actions'
import { JoinMode, modes } from '../../../../common/data/define/extra'
import { Option, OptionTarget } from '../../../../common/data/option'
import { Expression, OptionOperator } from '../../../../common/data/define/expression'
import { Translate, AtomOption, ConnectAtomOption, GroupParentheses } from '../../../../common/data/option/translate'